

spring:
  application:
    name: Spring03

  datasource:
    url: jdbc:postgresql://localhost:5432/library
    password: 12345
    username: librarian
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8888

library:
  allowed: 3


